/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */

#include "pypto/codegen/cce/cce_codegen.h"

#include <cstddef>
#include <ios>
#include <map>
#include <memory>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <utility>
#include <vector>

#include "pypto/backend/common/backend.h"
#include "pypto/backend/common/backend_config.h"
#include "pypto/codegen/orchestration/orchestration_codegen.h"
#include "pypto/core/error.h"
#include "pypto/core/logging.h"
#include "pypto/ir/expr.h"
#include "pypto/ir/function.h"
#include "pypto/ir/pipe.h"
#include "pypto/ir/program.h"
#include "pypto/ir/scalar_expr.h"
#include "pypto/ir/stmt.h"
#include "pypto/ir/transforms/passes.h"
#include "pypto/ir/type.h"

namespace pypto {
namespace codegen {

const char KERNEL_HEADER[] = R"(
#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif
)";

// Header for single-file mode (no tensor.h needed — uses direct __gm__ pointers)
const char KERNEL_HEADER_SINGLE[] = R"(
#include <cstdint>
#include <pto/pto-inst.hpp>

using namespace pto;
)";

CCECodegen::CCECodegen() : backend_(backend::GetBackend()) {
  auto type = backend::GetBackendType();
  CHECK(type == backend::BackendType::CCE)
      << "CCECodegen requires CCE backend, but " << (type == backend::BackendType::PTO ? "PTO" : "unknown")
      << " is configured";
}

std::map<std::string, std::string> CCECodegen::Generate(const ir::ProgramPtr& program) {
  CHECK(program != nullptr) << "Cannot generate code for null program";

  std::map<std::string, std::string> files;

  // Separate functions into kernel functions and orchestration functions
  std::vector<ir::FunctionPtr> kernel_functions;
  std::vector<ir::FunctionPtr> orchestration_functions;

  for (const auto& [gvar, func] : program->functions_) {
    if (func->func_type_ == ir::FunctionType::Orchestration) {
      orchestration_functions.push_back(func);
    } else {
      kernel_functions.push_back(func);
    }
  }

  // Generate kernel functions (CCE C++ code) to separate .cpp files in kernels/ subdirectory
  for (const auto& func : kernel_functions) {
    std::ostringstream oss;
    oss << "// Kernel Function: " << func->name_ << "\n";
    oss << "// Generated by PyPTO IR Compiler\n\n";
    oss << KERNEL_HEADER << "\n";

    std::string func_code = GenerateFunction(func);
    oss << func_code;

    auto core_type = InferFunctionCoreType(func);
    std::string core_type_str = core_type == ir::CoreType::VECTOR ? "aiv" : "aic";

    std::string filename = "kernels/" + core_type_str + "/" + func->name_ + ".cpp";
    files[filename] = oss.str();
  }

  // Generate orchestration function to orchestration/ subdirectory
  if (!orchestration_functions.empty()) {
    if (orchestration_functions.size() > 1) {
      throw pypto::ValueError("Program should have exactly one orchestration function, got " +
                              std::to_string(orchestration_functions.size()));
    }

    const auto& func = orchestration_functions[0];
    std::ostringstream oss;
    oss << "// Orchestration Function: " << func->name_ << "\n";
    oss << "// Generated by PyPTO IR Compiler\n\n";

    auto orch_result = GenerateOrchestration(program, func);
    oss << orch_result.code;

    std::string filename = "orchestration/" + func->name_ + ".cpp";
    files[filename] = oss.str();

    // Generate config file
    std::string config_code =
        GenerateConfigFile(func->name_, orch_result.func_name_to_id, orch_result.func_name_to_core_type);
    files["kernel_config.py"] = config_code;
  }

  return files;
}

std::string CCECodegen::GenerateConfigFile(
    const std::string& orch_func_name, const std::map<std::string, int>& func_name_to_id,
    const std::map<std::string, ir::CoreType>& func_name_to_core_type) {
  std::ostringstream oss;
  oss << "# Kernel and Orchestration Configuration\n\n";
  oss << "from pathlib import Path\n\n";
  oss << "_ROOT_DIR = Path(__file__).parent\n\n";

  oss << "# Runtime configuration for tensormap_and_ringbuffer\n";
  oss << "# This runtime requires 4 AICPU threads (3 schedulers + 1 orchestrator on thread 3)\n";
  oss << "RUNTIME_CONFIG = {\n";
  oss << "\t\"runtime\": \"tensormap_and_ringbuffer\",\n";
  oss << "\t\"aicpu_thread_num\": 4,\n";
  oss << "\t\"block_dim\": 24,\n";
  oss << "}\n\n";

  oss << "ORCHESTRATION = {\n\t\"source\": str(_ROOT_DIR / \"orchestration\" / \"" << orch_func_name
      << ".cpp\"),\n"
      << "\t\"function_name\": \"aicpu_orchestration_entry\"\n}\n\n";

  oss << "KERNELS = [\n";
  for (const auto& [name, id] : func_name_to_id) {
    std::string core_type = func_name_to_core_type.at(name) == ir::CoreType::VECTOR ? "aiv" : "aic";
    oss << "\t{\"func_id\": " << id << R"(, "source": str(_ROOT_DIR / "kernels" / ")" << core_type
        << "\" / \"" << name << R"(.cpp"), "core_type": ")" << core_type << "\"},\n";
  }
  oss << "]\n";
  return oss.str();
}

std::string CCECodegen::GenerateFunction(const ir::FunctionPtr& func) {
  CHECK(func != nullptr) << "Cannot generate code for null function";

  // Clear state
  emitter_.Clear();
  context_.Clear();

  // Generate prologue and body
  GeneratePrologue(func);
  GenerateBody(func);

  return emitter_.GetCode();
}

// ============================================================================
// Single-file MIX mode generation (skip ptoas)
// ============================================================================

std::string CCECodegen::GenerateSingle(const ir::ProgramPtr& program) {
  CHECK(program != nullptr) << "Cannot generate code for null program";

  // Run IR passes (same as PTOCodegen::Generate)
  ir::ProgramPtr lowered = ir::pass::LowerBreakContinue()(program);
  ir::ProgramPtr ssa_program = ir::pass::ConvertToSSA()(lowered);
  ir::ProgramPtr opt_program = ir::pass::ConstFoldAndSimplify()(ssa_program);

  // Find the kernel function (non-orchestration)
  ir::FunctionPtr kernel_func;
  for (const auto& [gvar, func] : opt_program->functions_) {
    if (func->func_type_ != ir::FunctionType::Orchestration) {
      kernel_func = func;
      break;
    }
  }
  CHECK(kernel_func != nullptr) << "No kernel function found in program";

  // Clear state
  emitter_.Clear();
  context_.Clear();
  single_file_mode_ = true;

  // Detect cross-core sync
  bool has_cross_sync = DetectCrossCoreSyncOps(kernel_func->body_);

  // Emit header (single-file mode: no tensor.h)
  emitter_.EmitLine(KERNEL_HEADER_SINGLE);

  // Generate prologue and body
  GenerateSinglePrologue(kernel_func, has_cross_sync);
  GenerateBody(kernel_func);

  single_file_mode_ = false;
  return emitter_.GetCode();
}

void CCECodegen::GenerateSinglePrologue(const ir::FunctionPtr& func, bool has_cross_sync) {
  // Collect dynamic dim variables from tensor shapes (first-occurrence order)
  std::vector<ir::VarPtr> dyn_dim_vars;
  std::set<std::string> seen_dyn_names;
  for (const auto& param : func->params_) {
    if (auto tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(param->GetType())) {
      for (const auto& dim_expr : tensor_type->shape_) {
        if (auto dim_var = std::dynamic_pointer_cast<const ir::Var>(dim_expr)) {
          if (seen_dyn_names.insert(dim_var->name_).second) {
            dyn_dim_vars.push_back(dim_var);
          }
        }
      }
    }
  }

  // Build PTO-style function signature: __global__ AICORE void func_name(__gm__ type* p1, ...)
  std::ostringstream sig;
  sig << "__global__ AICORE void " << func->name_ << "(";
  bool first = true;
  for (const auto& param : func->params_) {
    if (!first) sig << ", ";
    first = false;
    if (auto tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(param->GetType())) {
      std::string element_type = tensor_type->dtype_.ToCTypeString();
      std::string param_name = context_.SanitizeName(param);
      sig << "__gm__ " << element_type << "* " << param_name;
    } else if (auto scalar_type = std::dynamic_pointer_cast<const ir::ScalarType>(param->GetType())) {
      std::string cpp_type = scalar_type->dtype_.ToCTypeString();
      std::string param_name = context_.SanitizeName(param);
      sig << cpp_type << " " << param_name;
    } else if (auto ptr_type = std::dynamic_pointer_cast<const ir::PtrType>(param->GetType())) {
      std::string element_type = ptr_type->dtype_.ToCTypeString();
      std::string param_name = context_.SanitizeName(param);
      sig << "__gm__ " << element_type << "* " << param_name;
    }
  }
  // Append dynamic dim variables as int64_t parameters
  for (const auto& dyn_var : dyn_dim_vars) {
    if (!first) sig << ", ";
    first = false;
    sig << "int32_t " << context_.SanitizeName(dyn_var);
  }
  if (has_cross_sync) {
    if (!first) sig << ", ";
    sig << "__gm__ int64_t* ffts_addr";
  }
  sig << ")";

  emitter_.EmitLine(sig.str());
  emitter_.EmitLine("{");
  emitter_.IncreaseIndent();

  // Register dynamic dim variables in context (they are function args)
  for (const auto& dyn_var : dyn_dim_vars) {
    std::string name = context_.SanitizeName(dyn_var);
    context_.RegisterVar(dyn_var, name);
  }

  // Emit set_ffts_base_addr if cross-core sync
  if (has_cross_sync) {
    emitter_.EmitLine("set_ffts_base_addr((unsigned long)ffts_addr);");
    emitter_.EmitLine("");
  }

  // Collect access window shapes
  auto access_shapes = CollectTensorAccessShapes(func->body_);

  // Register parameters and emit GlobalTensor / scalar declarations
  for (size_t i = 0; i < func->params_.size(); ++i) {
    const auto& param = func->params_[i];
    const std::string param_name = context_.SanitizeName(param);

    if (auto tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(param->GetType())) {
      // Register with "Global" suffix
      const std::string global_name = param_name + "Global";
      context_.RegisterVar(param, global_name);

      // Look up access window shape
      std::optional<std::vector<ir::ExprPtr>> access_shape;
      auto it = access_shapes.find(param);
      if (it != access_shapes.end()) {
        access_shape = it->second;
      }

      // For single-file mode: GlobalTensor using direct pointer (no Tensor struct indirection)
      force_dn_layout_ = (dn_tensors_.count(param) > 0);
      GenerateGlobalTensorTypeDeclaration(global_name, tensor_type, param_name, std::nullopt, access_shape);
      force_dn_layout_ = false;
      emitter_.EmitLine("");
    } else if (auto scalar_type = std::dynamic_pointer_cast<const ir::ScalarType>(param->GetType())) {
      // Scalar params are direct function args
      context_.RegisterVar(param, param_name);
    }
  }

  // Collect tile sections for section-aware declarations
  auto tile_sections = CollectTileSections(func->body_);

  // Collect all TileType variables
  std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> tile_vars;
  if (func->body_) {
    tile_vars = CollectTileVariables(func->body_);
  }

  // Generate section-aware tile declarations
  if (!tile_vars.empty()) {
    // Separate tiles by section
    std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> cube_tiles;
    std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> vec_tiles;
    std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> shared_tiles;

    for (const auto& [var, tile_type] : tile_vars) {
      auto it = tile_sections.find(var);
      if (it != tile_sections.end()) {
        if (it->second == ir::SectionKind::Cube) {
          cube_tiles.emplace_back(var, tile_type);
        } else {
          vec_tiles.emplace_back(var, tile_type);
        }
      } else if (tile_type->memref_.has_value()) {
        // Infer section from memory space: Vec→Vector, everything else→Cube
        auto space = (*tile_type->memref_)->memory_space_;
        if (space == ir::MemorySpace::Vec) {
          vec_tiles.emplace_back(var, tile_type);
        } else {
          cube_tiles.emplace_back(var, tile_type);
        }
      } else {
        shared_tiles.emplace_back(var, tile_type);
      }
    }

    // Emit shared tiles (outside any #if)
    if (!shared_tiles.empty()) {
      emitter_.EmitLine("// Tile declarations (shared)");
      for (const auto& [var, tile_type] : shared_tiles) {
        const std::string var_name = context_.SanitizeName(var);
        GenerateTileTypeDeclaration(var_name, tile_type);
      }
      emitter_.EmitLine("");
    }

    // Emit Cube tiles inside #if defined(__DAV_CUBE__)
    if (!cube_tiles.empty()) {
      emitter_.EmitLine("#if defined(__DAV_CUBE__)");
      emitter_.EmitLine("// Tile declarations (Cube)");
      for (const auto& [var, tile_type] : cube_tiles) {
        const std::string var_name = context_.SanitizeName(var);
        GenerateTileTypeDeclaration(var_name, tile_type);
      }
      emitter_.EmitLine("#endif  // __DAV_CUBE__");
      emitter_.EmitLine("");
    }

    // Emit Vec tiles inside #if defined(__DAV_VEC__)
    if (!vec_tiles.empty()) {
      emitter_.EmitLine("#if defined(__DAV_VEC__)");
      emitter_.EmitLine("// Tile declarations (Vector)");
      for (const auto& [var, tile_type] : vec_tiles) {
        const std::string var_name = context_.SanitizeName(var);
        GenerateTileTypeDeclaration(var_name, tile_type);
      }
      emitter_.EmitLine("#endif  // __DAV_VEC__");
      emitter_.EmitLine("");
    }
  }

  emitter_.EmitLine("");
}

void CCECodegen::VisitStmt_(const ir::SectionStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null SectionStmt";

  if (single_file_mode_) {
    // Emit #if defined(__DAV_CUBE__) / #if defined(__DAV_VEC__)
    if (op->section_kind_ == ir::SectionKind::Cube) {
      emitter_.EmitLine("#if defined(__DAV_CUBE__)");
    } else {
      emitter_.EmitLine("#if defined(__DAV_VEC__)");
    }
  }

  // Visit the body
  if (op->body_) {
    VisitStmt(op->body_);
  }

  if (single_file_mode_) {
    if (op->section_kind_ == ir::SectionKind::Cube) {
      emitter_.EmitLine("#endif  // __DAV_CUBE__");
    } else {
      emitter_.EmitLine("#endif  // __DAV_VEC__");
    }
  }
}

bool CCECodegen::DetectCrossCoreSyncOps(const ir::StmtPtr& stmt) {
  if (!stmt) return false;

  class CrossCoreSyncDetector : public ir::IRVisitor {
   public:
    bool found = false;
    void VisitExpr_(const ir::CallPtr& op) override {
      const std::string& name = op->op_->name_;
      if (name == "system.set_cross_core" || name == "system.wait_cross_core" ||
          name == "system.set_cross_core_dyn" || name == "system.wait_cross_core_dyn") {
        found = true;
      }
      ir::IRVisitor::VisitExpr_(op);
    }
  };

  CrossCoreSyncDetector detector;
  detector.VisitStmt(stmt);
  return detector.found;
}

std::map<ir::VarPtr, ir::SectionKind> CCECodegen::CollectTileSections(const ir::StmtPtr& stmt) {
  if (!stmt) return {};

  class TileSectionCollector : public ir::IRVisitor {
   public:
    std::map<ir::VarPtr, ir::SectionKind> tile_sections;
    std::optional<ir::SectionKind> current_section;

    void VisitStmt_(const ir::SectionStmtPtr& op) override {
      auto prev = current_section;
      current_section = op->section_kind_;
      ir::IRVisitor::VisitStmt_(op);
      current_section = prev;
    }

    void VisitStmt_(const ir::AssignStmtPtr& op) override {
      auto tile_type = std::dynamic_pointer_cast<const ir::TileType>(op->var_->GetType());
      if (tile_type && current_section.has_value()) {
        tile_sections[op->var_] = *current_section;
      }
    }
  };

  TileSectionCollector collector;
  collector.VisitStmt(stmt);
  return collector.tile_sections;
}

void CCECodegen::GeneratePrologue(const ir::FunctionPtr& func) {
  // Function signature
  emitter_.EmitLine(
      "extern \"C\" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)");
  emitter_.EmitLine("{");
  emitter_.IncreaseIndent();

  emitter_.EmitLine("// Unpack arguments and type declarations");

  // Collect access window shapes so GlobalTensor Shape<> uses the block.load/store
  // window shape rather than the full tensor shape
  auto access_shapes = CollectTensorAccessShapes(func->body_);

  // First pass: Unpack arguments (use sanitized names but don't register yet)
  for (size_t i = 0; i < func->params_.size(); ++i) {
    const auto& param = func->params_[i];
    const std::string param_name = context_.SanitizeName(param);

    // tensor type parameter and type declaration
    if (auto tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(param->GetType())) {
      // Extract element type
      std::string element_type = tensor_type->dtype_.ToCTypeString();

      // Emit argument unpacking via Tensor* indirection
      std::string tensor_var = param_name + "_tensor";
      emitter_.EmitLine("__gm__ Tensor* " + tensor_var + " = reinterpret_cast<__gm__ Tensor*>(args[" +
                        std::to_string(i) + "]);");
      emitter_.EmitLine("__gm__ " + element_type + "* " + param_name + " = reinterpret_cast<__gm__ " +
                        element_type + "*>(" + tensor_var + "->buffer.addr);");

      // Register parameter with "Global" suffix for use in operations
      const std::string global_name = param_name + "Global";
      context_.RegisterVar(param, global_name);

      // Look up access window shape for GlobalTensor Shape<>/Stride<> generation
      std::optional<std::vector<ir::ExprPtr>> access_shape;
      auto it = access_shapes.find(param);
      if (it != access_shapes.end()) {
        access_shape = it->second;
      }

      GenerateGlobalTensorTypeDeclaration(global_name, tensor_type, param_name, tensor_var, access_shape);
    } else if (auto scalar_type = std::dynamic_pointer_cast<const ir::ScalarType>(param->GetType())) {
      // Generate scalar type declaration
      std::string cpp_type = scalar_type->dtype_.ToCTypeString();

      // Emit argument unpacking via union converter
      std::string conv_name = param_name + "_conv";
      emitter_.EmitLine("union { uint64_t u64; " + cpp_type + " val; } " + conv_name + ";");
      emitter_.EmitLine(conv_name + ".u64 = args[" + std::to_string(i) + "];");
      emitter_.EmitLine(cpp_type + " " + param_name + " = " + conv_name + ".val;");

      // Register scalar variable
      context_.RegisterVar(param, param_name);
    } else {
      throw pypto::RuntimeError("Unsupported parameter type in function " + func->name_);
    }

    emitter_.EmitLine("");
  }

  // Collect all TileType variables from function body
  std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> tile_vars;
  if (func->body_) {
    tile_vars = CollectTileVariables(func->body_);
  }

  // Generate Tile type definitions and allocations
  if (!tile_vars.empty()) {
    emitter_.EmitLine("// Tile type definitions and allocations");

    for (const auto& [var, tile_type] : tile_vars) {
      // Just use sanitized name (will be registered later in AssignStmt)
      const std::string var_name = context_.SanitizeName(var);

      // Generate Tile type and declaration (memref extracted automatically from tile_type)
      GenerateTileTypeDeclaration(var_name, tile_type);
    }

    emitter_.EmitLine("");
  }

  emitter_.EmitLine("");
}

void CCECodegen::GenerateBody(const ir::FunctionPtr& func) {
  emitter_.EmitLine("// Function body");
  if (func->body_) {
    VisitStmt(func->body_);
  }

  emitter_.DecreaseIndent();
  emitter_.EmitLine("}");
}

void CCECodegen::VisitStmt_(const ir::AssignStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null AssignStmt";
  INTERNAL_CHECK(op->var_ != nullptr) << "Internal error: AssignStmt has null variable";
  INTERNAL_CHECK(op->value_ != nullptr) << "Internal error: AssignStmt has null value";

  // Skip TupleGetItemExpr assignments that extract Tiles/sub-tuples from make_tile tuples.
  // The tiles are already declared in the prologue with correct memref addresses.
  // Also skip assignments of TupleType/TileType values from make_tile no-ops.
  if (ir::As<ir::TupleGetItemExpr>(op->value_)) {
    auto result_type = op->value_->GetType();
    bool is_tile_related = ir::As<ir::TileType>(result_type) != nullptr;
    if (!is_tile_related) {
      // Check if TupleType ultimately contains TileTypes (nested make_tile result)
      if (auto tuple_type = ir::As<ir::TupleType>(result_type)) {
        is_tile_related = true;  // Any tuple from TupleGetItemExpr in tile context is make_tile related
      }
    }
    if (is_tile_related) {
      std::string var_name = context_.SanitizeName(op->var_);
      context_.RegisterVar(op->var_, var_name);
      // Propagate tile addresses from the prologue-declared tiles
      // e.g., q_mat_buf_0 → _tuple_tmp_0_0 (which has address 0x0)
      // The TupleGetItemExpr naming gives us _tuple_tmp_0_0 etc.
      auto tge = ir::As<ir::TupleGetItemExpr>(op->value_);
      if (tge) {
        // Evaluate what the TupleGetItemExpr resolves to (e.g., "_tuple_tmp_0_0")
        VisitExpr(op->value_);
        std::string resolved = current_expr_value_;
        current_expr_value_ = "";
        if (tile_addresses_.count(resolved)) {
          tile_addresses_[var_name] = tile_addresses_[resolved];
        }
      }
      current_target_var_ = "";
      return;
    }
  }
  // Also skip make_tile no-op assignments (value is a Call to make_tile → returns "")
  // and TupleType assignments from SSA yield that carry tiles
  if (ir::As<ir::TupleType>(op->var_->GetType())) {
    std::string var_name = context_.SanitizeName(op->var_);
    context_.RegisterVar(op->var_, var_name);
    current_target_var_ = var_name;
    current_expr_value_ = "";
    VisitExpr(op->value_);
    // Don't emit assignment — tuple is just a grouping of tiles
    current_expr_value_ = "";
    current_target_var_ = "";
    return;
  }

  // Sanitize and register the variable name
  std::string var_name = context_.SanitizeName(op->var_);
  context_.RegisterVar(op->var_, var_name);

  // Set context for expression visitor (dual-mode pattern)
  current_target_var_ = var_name;
  current_expr_value_ = "";

  // Dispatch to type-specific expression handler
  VisitExpr(op->value_);

  // If expression was non-Call (returned a value), emit assignment
  if (!current_expr_value_.empty()) {
    // For tile variables assigned from another tile: register as alias (no code emitted).
    // The source tile was already properly TASSIGN'd (possibly conditionally).
    // Using operator= or static TASSIGN would lose the runtime-selected address.
    auto var_type = op->var_->GetType();
    if (ir::As<ir::Var>(op->value_) &&
        (ir::As<ir::TileType>(var_type) || ir::As<ir::TupleType>(var_type))) {
      // Just alias: make var_name resolve to the same C++ name as the source
      context_.RegisterVar(op->var_, current_expr_value_);
      if (tile_addresses_.count(current_expr_value_)) {
        tile_addresses_[var_name] = tile_addresses_[current_expr_value_];
      }
      current_expr_value_ = "";
      current_target_var_ = "";
      return;
    }
    emitter_.EmitLine("auto " + var_name + " = " + current_expr_value_ + ";");
    current_expr_value_ = "";
  }

  // Clear context
  current_target_var_ = "";
}

void CCECodegen::VisitStmt_(const ir::EvalStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null EvalStmt";
  INTERNAL_CHECK(op->expr_ != nullptr) << "Internal error: EvalStmt has null expression";

  // EvalStmt: evaluate expression for side effects (e.g., sync operations)
  // Sync ops (set_flag, wait_flag, pipe_barrier) are registered with f_codegen_cce
  // and will be invoked via VisitExpr_(Call)
  VisitExpr(op->expr_);
}

void CCECodegen::VisitStmt_(const ir::ReturnStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ReturnStmt";
  // For void functions, we don't need to generate anything
  // The function will return implicitly at the closing brace
}

void CCECodegen::VisitStmt_(const ir::YieldStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null YieldStmt";

  if (op->value_.empty()) {
    return;  // No values to yield
  }

  // Visit each yielded expression and collect values
  std::vector<std::string> yielded_values;
  for (const auto& expr : op->value_) {
    VisitExpr(expr);
    yielded_values.push_back(current_expr_value_);
  }

  // Store in temporary buffer for ForStmt to pick up
  yield_buffer_ = yielded_values;
  current_expr_value_ = "";
}

void CCECodegen::VisitStmt_(const ir::IfStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null IfStmt";
  INTERNAL_CHECK(op->condition_ != nullptr) << "Internal error: IfStmt has null condition";
  INTERNAL_CHECK(op->then_body_ != nullptr) << "Internal error: IfStmt has null then_body";

  // Declare and register return variables BEFORE the if statement
  for (const auto& return_var : op->return_vars_) {
    std::string return_var_name = context_.SanitizeName(return_var);
    context_.RegisterVar(return_var, return_var_name);

    // Generate appropriate type declaration based on variable type
    if (auto tile_type = std::dynamic_pointer_cast<const ir::TileType>(return_var->GetType())) {
      // Declare tile WITHOUT TASSIGN — the if/else body will TASSIGN the correct address.
      {
        std::vector<int64_t> shape_dims = ExtractShapeDimensions(tile_type->shape_);
        int64_t rows = shape_dims.size() >= 1 ? shape_dims[0] : 1;
        int64_t cols = shape_dims.size() >= 2 ? shape_dims[1] : 1;
        std::string type_alias_name = return_var_name + "Type";
        std::string tile_type_str = type_converter_.ConvertTileType(tile_type, rows, cols);
        emitter_.EmitLine("using " + type_alias_name + " = " + tile_type_str + ";");
        emitter_.EmitLine(type_alias_name + " " + return_var_name + "(" +
                          std::to_string(rows) + ", " + std::to_string(cols) + ");");
      }
    } else if (auto tensor_type = std::dynamic_pointer_cast<const ir::TensorType>(return_var->GetType())) {
      // GlobalTensor variables are uninitialized at declaration (no base_pointer)
      GenerateGlobalTensorTypeDeclaration(return_var_name, tensor_type);
    } else if (auto scalar_type = std::dynamic_pointer_cast<const ir::ScalarType>(return_var->GetType())) {
      // Generate scalar type declaration
      std::string cpp_type = scalar_type->dtype_.ToCTypeString();
      emitter_.EmitLine(cpp_type + " " + return_var_name + ";");
    } else {
      throw pypto::RuntimeError("Unsupported return_var type in IfStmt");
    }
  }

  if (!op->return_vars_.empty()) {
    emitter_.EmitLine("");  // Blank line for clarity
  }

  // Evaluate condition
  VisitExpr(op->condition_);
  std::string condition = current_expr_value_;
  current_expr_value_ = "";

  // Emit if statement
  emitter_.EmitLine("if (" + condition + ") {");
  emitter_.IncreaseIndent();

  // Visit then branch
  VisitStmt(op->then_body_);

  // Assign return variables from then branch yield
  if (!op->return_vars_.empty() && !yield_buffer_.empty()) {
    for (size_t i = 0; i < op->return_vars_.size(); ++i) {
      const auto& return_var = op->return_vars_[i];
      std::string return_var_name = context_.SanitizeName(return_var);
      std::string yielded_value = yield_buffer_[i];

      // For TileType: use TASSIGN to transfer hardware address instead of operator=
      auto return_type = return_var->GetType();
      if ((ir::As<ir::TileType>(return_type) || ir::As<ir::TupleType>(return_type)) &&
          tile_addresses_.count(yielded_value)) {
        emitter_.EmitLine("TASSIGN(" + return_var_name + ", " + tile_addresses_[yielded_value] + ");");
        tile_addresses_[return_var_name] = tile_addresses_[yielded_value];
      } else {
        emitter_.EmitLine(return_var_name + " = " + yielded_value + ";");
      }

      // If the yielded value is a TensorType (GlobalTensor), inherit pointer and Tensor struct mappings
      if (std::dynamic_pointer_cast<const ir::TensorType>(return_type)) {
        std::string yielded_ptr = context_.GetPointer(yielded_value);
        context_.RegisterPointer(return_var_name, yielded_ptr);

        if (!single_file_mode_) {
          std::string yielded_struct = context_.GetTensorStruct(yielded_value);
          context_.RegisterTensorStruct(return_var_name, yielded_struct);
        }
      }
    }
    yield_buffer_.clear();
  }

  emitter_.DecreaseIndent();

  // Emit else branch if present
  if (op->else_body_.has_value()) {
    emitter_.EmitLine("} else {");
    emitter_.IncreaseIndent();

    VisitStmt(*op->else_body_);  // NOLINT(bugprone-unchecked-optional-access)

    // Assign return variables from else branch yield
    if (!op->return_vars_.empty() && !yield_buffer_.empty()) {
      for (size_t i = 0; i < op->return_vars_.size(); ++i) {
        const auto& return_var = op->return_vars_[i];
        std::string return_var_name = context_.SanitizeName(return_var);
        std::string yielded_value = yield_buffer_[i];

        // For TileType: use TASSIGN to transfer hardware address instead of operator=
        auto return_type = return_var->GetType();
        if ((ir::As<ir::TileType>(return_type) || ir::As<ir::TupleType>(return_type)) &&
            tile_addresses_.count(yielded_value)) {
          emitter_.EmitLine("TASSIGN(" + return_var_name + ", " + tile_addresses_[yielded_value] + ");");
          tile_addresses_[return_var_name] = tile_addresses_[yielded_value];
        } else {
          emitter_.EmitLine(return_var_name + " = " + yielded_value + ";");
        }

        // If the yielded value is a TensorType (GlobalTensor), inherit pointer and Tensor struct mappings
        if (std::dynamic_pointer_cast<const ir::TensorType>(return_type)) {
          std::string yielded_ptr = context_.GetPointer(yielded_value);
          context_.RegisterPointer(return_var_name, yielded_ptr);

          if (!single_file_mode_) {
            std::string yielded_struct = context_.GetTensorStruct(yielded_value);
            context_.RegisterTensorStruct(return_var_name, yielded_struct);
          }
        }
      }
      yield_buffer_.clear();
    }

    emitter_.DecreaseIndent();
  }

  emitter_.EmitLine("}");
  emitter_.EmitLine("");
}

void CCECodegen::VisitStmt_(const ir::ForStmtPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ForStmt";
  INTERNAL_CHECK(op->loop_var_ != nullptr) << "Internal error: ForStmt has null loop_var";
  INTERNAL_CHECK(op->start_ != nullptr) << "Internal error: ForStmt has null start";
  INTERNAL_CHECK(op->stop_ != nullptr) << "Internal error: ForStmt has null stop";
  INTERNAL_CHECK(op->step_ != nullptr) << "Internal error: ForStmt has null step";
  INTERNAL_CHECK(op->body_ != nullptr) << "Internal error: ForStmt has null body";

  // Check consistency: iter_args and return_vars must have same size
  CHECK(op->iter_args_.size() == op->return_vars_.size())
      << "ForStmt iter_args size (" << op->iter_args_.size() << ") must equal return_vars size ("
      << op->return_vars_.size() << ")";

  if (op->kind_ == ir::ForKind::Unroll) {
    LOG_WARN << "ForKind::Unroll loop was not expanded before codegen; "
                "generating sequential loop as fallback";
  }

  // Register loop variable
  std::string loop_var_name = context_.SanitizeName(op->loop_var_);
  context_.RegisterVar(op->loop_var_, loop_var_name);

  // Register iteration arguments (loop-carried values)
  std::vector<std::string> iter_arg_names;
  if (!op->iter_args_.empty()) {
    emitter_.EmitLine("// Loop-carried values initialization");
    for (auto& iter_arg : op->iter_args_) {
      std::string iter_arg_name = context_.SanitizeName(iter_arg);
      context_.RegisterVar(iter_arg, iter_arg_name);
      iter_arg_names.push_back(iter_arg_name);

      // Initialize from IterArg's initValue
      VisitExpr(iter_arg->initValue_);
      std::string init_value = current_expr_value_;
      current_expr_value_ = "";

      // If initializing from a tensor variable, inherit both pointer and Tensor struct mappings
      auto init_var = std::dynamic_pointer_cast<const ir::Var>(iter_arg->initValue_);
      if (init_var && std::dynamic_pointer_cast<const ir::TensorType>(init_var->GetType())) {
        std::string init_var_name = context_.GetVarName(init_var);
        std::string init_ptr = context_.GetPointer(init_var_name);
        context_.RegisterPointer(iter_arg_name, init_ptr);

        if (!single_file_mode_) {
          std::string init_struct = context_.GetTensorStruct(init_var_name);
          context_.RegisterTensorStruct(iter_arg_name, init_struct);
        }
      }

      iter_arg_name += " = ";
      iter_arg_name += init_value;
      iter_arg_name += ";";
      emitter_.EmitLine("auto " + iter_arg_name);
    }
    emitter_.EmitLine("");
  }

  // Evaluate loop range
  VisitExpr(op->start_);
  std::string start = current_expr_value_;
  current_expr_value_ = "";

  VisitExpr(op->stop_);
  std::string stop = current_expr_value_;
  current_expr_value_ = "";

  VisitExpr(op->step_);
  std::string step = current_expr_value_;
  current_expr_value_ = "";

  // Emit for loop
  emitter_.EmitLine("for (uint64_t " + loop_var_name + " = " + start + "; " + loop_var_name + " < " + stop +
                    "; " + loop_var_name + " += " + step + ") {");
  emitter_.IncreaseIndent();

  // Visit loop body
  // Note: Do NOT clear yield_buffer before visiting body - it should persist
  // across the body visit but be cleared AFTER in case of multiple loop executions
  yield_buffer_.clear();
  VisitStmt(op->body_);

  // If iter_args exist and yield was called, assign yielded values
  if (!op->iter_args_.empty() && !yield_buffer_.empty()) {
    CHECK(yield_buffer_.size() == iter_arg_names.size())
        << "Yielded " << yield_buffer_.size() << " values but expected " << iter_arg_names.size();

    for (size_t i = 0; i < iter_arg_names.size(); ++i) {
      // For tiles: use TASSIGN instead of operator= to transfer hardware address
      if (tile_addresses_.count(yield_buffer_[i])) {
        emitter_.EmitLine("TASSIGN(" + iter_arg_names[i] + ", " + tile_addresses_[yield_buffer_[i]] + ");");
        tile_addresses_[iter_arg_names[i]] = tile_addresses_[yield_buffer_[i]];
      } else {
        emitter_.EmitLine(iter_arg_names[i] + " = " + yield_buffer_[i] + ";");
      }
    }
  }
  yield_buffer_.clear();

  emitter_.DecreaseIndent();
  emitter_.EmitLine("}");
  emitter_.EmitLine("");

  // Register return variables with same names as iter_args
  // (return_vars represent the final values of iter_args after loop completion)
  if (!op->return_vars_.empty()) {
    for (size_t i = 0; i < op->return_vars_.size(); ++i) {
      const auto& return_var = op->return_vars_[i];
      // Register return_var with the iter_arg's name
      // They represent the same value, so no assignment needed
      if (i < iter_arg_names.size()) {
        context_.RegisterVar(return_var, iter_arg_names[i]);
      } else {
        // No corresponding iter_arg (shouldn't happen if CHECK above passes)
        throw pypto::RuntimeError("ForStmt return_var has no corresponding iter_arg");
      }
    }
  }
}

void CCECodegen::VisitStmt_(const ir::WhileStmtPtr& op) {
  throw pypto::RuntimeError("WhileStmt codegen not yet implemented");
}

// ========================================================================
// Expression Visitor Methods - Dual-Mode Pattern
// ========================================================================
// - Statement-Emitting Mode (Call): Uses current_target_var_, emits instructions
// - Value-Returning Mode (others): Sets current_expr_value_ with inline C++ code

// ---- Leaf Nodes ----

void CCECodegen::VisitExpr_(const ir::VarPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Var";
  current_expr_value_ = context_.GetVarName(op);
}

void CCECodegen::VisitExpr_(const ir::IterArgPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null IterArg";
  // IterArg inherits from Var, treated same way
  current_expr_value_ = context_.GetVarName(std::dynamic_pointer_cast<const ir::Var>(op));
}

void CCECodegen::VisitExpr_(const ir::ConstIntPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ConstInt";
  current_expr_value_ = std::to_string(op->value_);
}

void CCECodegen::VisitExpr_(const ir::ConstFloatPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ConstFloat";
  current_expr_value_ = std::to_string(op->value_);
}

void CCECodegen::VisitExpr_(const ir::ConstBoolPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null ConstBool";
  current_expr_value_ = op->value_ ? "true" : "false";
}

void CCECodegen::VisitExpr_(const ir::TupleGetItemExprPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null TupleGetItemExpr";

  // If the tuple is a MakeTuple literal, just evaluate the specific element directly.
  // This handles constant tuples like event_ids = (0, 1).
  if (auto make_tuple = ir::As<ir::MakeTuple>(op->tuple_)) {
    CHECK(op->index_ >= 0 && op->index_ < static_cast<int>(make_tuple->elements_.size()))
        << "TupleGetItemExpr index " << op->index_ << " out of bounds";
    VisitExpr(make_tuple->elements_[op->index_]);
    return;
  }

  VisitExpr(op->tuple_);
  std::string tuple_name = current_expr_value_;

  auto tuple_type = op->tuple_->GetType();
  // For TupleType/TileType tuples (from make_tile, double-buffer patterns):
  // Elements are declared as separate tiles with "_idx" suffix in prologue.
  if (std::dynamic_pointer_cast<const ir::TupleType>(tuple_type) ||
      std::dynamic_pointer_cast<const ir::TileType>(tuple_type)) {
    current_expr_value_ = tuple_name + "_" + std::to_string(op->index_);
    return;
  }

  current_expr_value_ = tuple_name + "[" + std::to_string(op->index_) + "]";
}

// ========================================================================
// CodegenBase interface and CCE-specific helper methods
// ========================================================================

std::string CCECodegen::GetExprAsCode(const ir::ExprPtr& expr) {
  VisitExpr(expr);
  return current_expr_value_;
}

void CCECodegen::Emit(const std::string& line) { emitter_.EmitLine(line); }

std::string CCECodegen::GetTypeString(const DataType& dtype) const { return dtype.ToCTypeString(); }

int64_t CCECodegen::GetConstIntValue(const ir::ExprPtr& expr) { return ExtractConstInt(expr); }

std::string CCECodegen::GetVarName(const ir::VarPtr& var) { return context_.GetVarName(var); }

std::string CCECodegen::GetPointer(const std::string& var_name) { return context_.GetPointer(var_name); }

std::string CCECodegen::ComputeIRBasedOffset(const ir::TensorTypePtr& tensor_type,
                                             const ir::MakeTuplePtr& offsets) {
  // Compute row-major strides from IR tensor shape and build offset expression.
  // For tensor shape [d0, d1, ..., dn-1]:
  //   stride[i] = d_{i+1} * d_{i+2} * ... * d_{n-1}
  //   stride[n-1] = 1
  //   offset = off[0]*stride[0] + off[1]*stride[1] + ...
  size_t ndim = tensor_type->shape_.size();
  CHECK(offsets->elements_.size() == ndim)
      << "Offset dimensions (" << offsets->elements_.size() << ") != tensor dimensions (" << ndim << ")";

  std::ostringstream result;
  result << "(";
  bool first = true;
  for (size_t i = 0; i < ndim; ++i) {
    std::string off_expr = GetExprAsCode(offsets->elements_[i]);

    // Build stride as product of shape[i+1..n-1]
    // For the last dimension, stride = 1, so just add the offset directly
    if (!first) result << " + ";
    first = false;
    result << off_expr;

    for (size_t j = i + 1; j < ndim; ++j) {
      result << " * " << GetExprAsCode(tensor_type->shape_[j]);
    }
  }
  result << ")";
  return result.str();
}

void CCECodegen::RegisterOutputPointer(const std::string& output_var_name,
                                       const std::string& tensor_var_name) {
  context_.RegisterPointer(output_var_name, tensor_var_name);
}

std::string CCECodegen::GetTensorStruct(const std::string& var_name) {
  return context_.GetTensorStruct(var_name);
}

void CCECodegen::RegisterOutputTensorStruct(const std::string& output_var_name,
                                            const std::string& tensor_var_name) {
  context_.RegisterTensorStruct(output_var_name, tensor_var_name);
}

// ========================================================================
// Call Expression Visitor (uses operator registry codegen functions)
// ========================================================================

void CCECodegen::VisitExpr_(const ir::CallPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Call";

  CHECK(backend_ != nullptr) << "CCE backend must not be null";
  const auto* op_info = backend_->GetOpInfo(op->op_->name_);
  if (op_info == nullptr) {
    ThrowNoCodegenForCall(op->op_->name_);
  }
  std::string result = op_info->codegen_func(op, *this);
  current_expr_value_ = result;
}

// ---- Binary Operators ----

#define IMPLEMENT_BINARY_OP(OpType, OpName, CppOp)                        \
  void CCECodegen::VisitExpr_(const ir::OpType##Ptr& op) {                \
    INTERNAL_CHECK(op != nullptr) << "Internal error: null " << (OpName); \
    VisitExpr(op->left_);                                                 \
    std::string left = current_expr_value_;                               \
    VisitExpr(op->right_);                                                \
    std::string right = current_expr_value_;                              \
    current_expr_value_ = "(" + left + " " + (CppOp) + " " + right + ")"; \
  }

// Arithmetic operators
IMPLEMENT_BINARY_OP(Add, "Add", "+")
IMPLEMENT_BINARY_OP(Sub, "Sub", "-")
IMPLEMENT_BINARY_OP(Mul, "Mul", "*")
IMPLEMENT_BINARY_OP(FloorDiv, "FloorDiv", "/")
IMPLEMENT_BINARY_OP(FloorMod, "FloorMod", "%")
IMPLEMENT_BINARY_OP(FloatDiv, "FloatDiv", "/")

// Comparison operators
IMPLEMENT_BINARY_OP(Eq, "Eq", "==")
IMPLEMENT_BINARY_OP(Ne, "Ne", "!=")
IMPLEMENT_BINARY_OP(Lt, "Lt", "<")
IMPLEMENT_BINARY_OP(Le, "Le", "<=")
IMPLEMENT_BINARY_OP(Gt, "Gt", ">")
IMPLEMENT_BINARY_OP(Ge, "Ge", ">=")

// Logical operators
IMPLEMENT_BINARY_OP(And, "And", "&&")
IMPLEMENT_BINARY_OP(Or, "Or", "||")
IMPLEMENT_BINARY_OP(Xor, "Xor", "^")

// Bitwise operators
IMPLEMENT_BINARY_OP(BitAnd, "BitAnd", "&")
IMPLEMENT_BINARY_OP(BitOr, "BitOr", "|")
IMPLEMENT_BINARY_OP(BitXor, "BitXor", "^")
IMPLEMENT_BINARY_OP(BitShiftLeft, "BitShiftLeft", "<<")
IMPLEMENT_BINARY_OP(BitShiftRight, "BitShiftRight", ">>")

#undef IMPLEMENT_BINARY_OP

// Special binary operators (function calls)
void CCECodegen::VisitExpr_(const ir::MinPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Min";
  VisitExpr(op->left_);
  std::string left = current_expr_value_;
  VisitExpr(op->right_);
  std::string right = current_expr_value_;
  current_expr_value_ = "min(" + left + ", " + right + ")";
}

void CCECodegen::VisitExpr_(const ir::MaxPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Max";
  VisitExpr(op->left_);
  std::string left = current_expr_value_;
  VisitExpr(op->right_);
  std::string right = current_expr_value_;
  current_expr_value_ = "max(" + left + ", " + right + ")";
}

void CCECodegen::VisitExpr_(const ir::PowPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Pow";
  VisitExpr(op->left_);
  std::string left = current_expr_value_;
  VisitExpr(op->right_);
  std::string right = current_expr_value_;
  current_expr_value_ = "pow(" + left + ", " + right + ")";
}

// ---- Unary Operators ----

#define IMPLEMENT_UNARY_OP(OpType, OpName, CppOp)                                 \
  void CCECodegen::VisitExpr_(const ir::OpType##Ptr& op) {                        \
    INTERNAL_CHECK(op != nullptr) << "Internal error: null " << (OpName);         \
    VisitExpr(op->operand_);                                                      \
    current_expr_value_ = std::string("(") + (CppOp) + current_expr_value_ + ")"; \
  }

IMPLEMENT_UNARY_OP(Neg, "Neg", "-")
IMPLEMENT_UNARY_OP(Not, "Not", "!")
IMPLEMENT_UNARY_OP(BitNot, "BitNot", "~")

#undef IMPLEMENT_UNARY_OP

// Special unary operators
void CCECodegen::VisitExpr_(const ir::AbsPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Abs";
  VisitExpr(op->operand_);
  std::string operand = current_expr_value_;
  current_expr_value_ = "abs(" + operand + ")";
}

void CCECodegen::VisitExpr_(const ir::CastPtr& op) {
  INTERNAL_CHECK(op != nullptr) << "Internal error: null Cast";
  VisitExpr(op->operand_);
  std::string operand = current_expr_value_;

  auto scalar_type = std::dynamic_pointer_cast<const ir::ScalarType>(op->GetType());
  CHECK(scalar_type != nullptr) << "Cast target must be ScalarType";

  std::string cpp_type = scalar_type->dtype_.ToCTypeString();
  current_expr_value_ = "((" + cpp_type + ")" + operand + ")";
}

// ========================================================================
// End of Expression Visitor Methods
// ========================================================================

int64_t CCECodegen::ExtractConstInt(const ir::ExprPtr& expr) {
  auto const_int = std::dynamic_pointer_cast<const ir::ConstInt>(expr);
  CHECK(const_int != nullptr) << "Expected constant integer expression";
  return const_int->value_;
}

namespace {

/**
 * @brief Helper visitor for collecting TileType variables from IR
 *
 * Traverses the IR tree and collects all variables with TileType.
 * Uses the visitor pattern for clean, extensible traversal.
 */
class TileCollector : public ir::IRVisitor {
 public:
  std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> tile_vars_;

  // Extract the first TileType from a possibly nested TupleType
  static ir::TileTypePtr ExtractLeafTileType(const ir::TypePtr& type) {
    if (auto tile = std::dynamic_pointer_cast<const ir::TileType>(type)) {
      return tile;
    }
    if (auto tuple = std::dynamic_pointer_cast<const ir::TupleType>(type)) {
      for (const auto& elem : tuple->types_) {
        auto result = ExtractLeafTileType(elem);
        if (result) return result;
      }
    }
    return nullptr;
  }

  // Recursively collect all TileTypes from a type (handles TupleType nesting)
  static void CollectTileTypesFromType(const ir::TypePtr& type, std::vector<ir::TileTypePtr>& result) {
    if (auto tile = std::dynamic_pointer_cast<const ir::TileType>(type)) {
      result.push_back(tile);
    } else if (auto tuple = std::dynamic_pointer_cast<const ir::TupleType>(type)) {
      for (const auto& elem : tuple->types_) {
        CollectTileTypesFromType(elem, result);
      }
    }
  }

  void VisitStmt_(const ir::AssignStmtPtr& op) override {
    auto var_type = op->var_->GetType();
    // Direct TileType variable
    if (auto tile_type = std::dynamic_pointer_cast<const ir::TileType>(var_type)) {
      tile_vars_.emplace_back(op->var_, tile_type);
      return;
    }
    // TupleType variable (from make_tile or double-buffer patterns):
    // Expand each TileType element as a separate tile with indexed name.
    if (std::dynamic_pointer_cast<const ir::TupleType>(var_type)) {
      std::vector<ir::TileTypePtr> tile_types;
      CollectTileTypesFromType(var_type, tile_types);
      for (size_t i = 0; i < tile_types.size(); ++i) {
        // Create a synthetic Var for each tuple element: varname_0, varname_1, ...
        auto elem_var = std::make_shared<ir::Var>(
            op->var_->name_ + "_" + std::to_string(i), tile_types[i], op->var_->span_);
        tile_vars_.emplace_back(elem_var, tile_types[i]);
      }
    }
  }
};

/**
 * @brief Helper visitor for collecting tensor access shapes from block.load/store
 *
 * Traverses the IR tree to find block.load/block.store/block.l0c_store calls
 * and extracts the access window shapes (shapes_tuple) for each tensor parameter.
 * The GlobalTensor shape should match the access window, not the full tensor shape.
 */
class TensorAccessShapeCollector : public ir::IRVisitor {
 public:
  std::map<ir::VarPtr, std::vector<ir::ExprPtr>> access_shapes_;
  std::set<ir::VarPtr> dn_tensors_;  // tensors loaded with layout="dn"

  void VisitExpr_(const ir::CallPtr& op) override {
    const std::string& op_name = op->op_->name_;

    // Determine tensor arg index and shapes arg index:
    // block.load / manual.load: tensor at arg[0], shapes at arg[2]
    // block.store / block.l0c_store / manual.store / manual.l0c_store: tensor at arg[3], shapes at arg[2]
    int tensor_arg_idx = -1;
    int shapes_arg_idx = 2;
    if (op_name == "block.load" || op_name == "manual.load") {
      tensor_arg_idx = 0;
    } else if (op_name == "block.store" || op_name == "block.l0c_store" || op_name == "manual.store" ||
               op_name == "manual.l0c_store") {
      tensor_arg_idx = 3;
    }

    if (tensor_arg_idx >= 0) {
      INTERNAL_CHECK(op->args_.size() > 2 && tensor_arg_idx < static_cast<int>(op->args_.size()))
          << "Internal error: " << op_name << " has unexpected argument count: " << op->args_.size();
      auto tensor_var = std::dynamic_pointer_cast<const ir::Var>(op->args_[tensor_arg_idx]);
      auto shapes_tuple = std::dynamic_pointer_cast<const ir::MakeTuple>(op->args_[shapes_arg_idx]);
      if (tensor_var && access_shapes_.find(tensor_var) == access_shapes_.end()) {
        if (shapes_tuple && !shapes_tuple->elements_.empty()) {
          access_shapes_[tensor_var] = shapes_tuple->elements_;
        } else {
          int tile_idx = (tensor_arg_idx == 0) ? 3 : 0;
          if (tile_idx < static_cast<int>(op->args_.size())) {
            auto tile_type = std::dynamic_pointer_cast<const ir::TileType>(op->args_[tile_idx]->GetType());
            if (tile_type) {
              access_shapes_[tensor_var] = tile_type->shape_;
            }
          }
        }
        // Detect DN layout from manual.load kwargs
        if (tensor_var && (op_name == "manual.load" || op_name == "block.load")) {
          if (op->HasKwarg("layout") && op->GetKwarg<std::string>("layout") == "dn") {
            dn_tensors_.insert(tensor_var);
          }
        }
      }
    }

    ir::IRVisitor::VisitExpr_(op);
  }
};

}  // namespace

std::vector<std::pair<ir::VarPtr, ir::TileTypePtr>> CCECodegen::CollectTileVariables(
    const ir::StmtPtr& stmt) {
  if (!stmt) {
    return {};
  }

  TileCollector collector;
  collector.VisitStmt(stmt);
  return collector.tile_vars_;
}

std::map<ir::VarPtr, std::vector<ir::ExprPtr>> CCECodegen::CollectTensorAccessShapes(
    const ir::StmtPtr& stmt) {
  if (!stmt) {
    return {};
  }

  TensorAccessShapeCollector collector;
  collector.VisitStmt(stmt);
  dn_tensors_ = collector.dn_tensors_;
  return collector.access_shapes_;
}

std::vector<int64_t> CCECodegen::ExtractShapeDimensions(const std::vector<ir::ExprPtr>& shape_exprs) {
  std::vector<int64_t> dims;
  dims.reserve(shape_exprs.size());
  for (const auto& expr : shape_exprs) {
    dims.push_back(ExtractConstInt(expr));
  }
  return dims;
}

std::string CCECodegen::FormatAddressHex(int64_t addr) {
  std::ostringstream oss;
  oss << "0x" << std::hex << addr;
  return oss.str();
}

void CCECodegen::GenerateTileTypeDeclaration(const std::string& var_name, const ir::TileTypePtr& tile_type) {
  INTERNAL_CHECK(!var_name.empty()) << "Internal error: var_name cannot be empty";
  INTERNAL_CHECK(tile_type != nullptr) << "Internal error: tile_type is null";

  // Extract tile shape dimensions
  std::vector<int64_t> shape_dims = ExtractShapeDimensions(tile_type->shape_);

  // CCE codegen only supports 1D and 2D tiles
  CHECK(shape_dims.size() <= 2) << "CCE codegen only supports 1D and 2D TileType, but got "
                                << shape_dims.size()
                                << " dimensions. Multi-dimensional tiles (>2D) are supported at IR level "
                                << "but not yet in code generation.";

  // Determine tile dimensions (default to 1 if not specified)
  int64_t rows = shape_dims.size() >= 1 ? shape_dims[0] : 1;
  int64_t cols = shape_dims.size() >= 2 ? shape_dims[1] : 1;

  // Generate Tile type alias
  std::string type_alias_name = var_name + "Type";
  std::string tile_type_str = type_converter_.ConvertTileType(tile_type, rows, cols);
  std::ostringstream type_alias;
  type_alias << "using " << type_alias_name << " = " << tile_type_str << ";";
  emitter_.EmitLine(type_alias.str());

  // Generate Tile instance with runtime valid shape (v_row=-1, v_col=-1 → constructor(VR, VC))
  std::ostringstream tile_instance;
  tile_instance << type_alias_name << " " << var_name << "(" << rows << ", " << cols << ");";
  emitter_.EmitLine(tile_instance.str());

  // Generate TASSIGN if tile_type has memref
  if (tile_type->memref_.has_value()) {
    int64_t addr =
        ExtractConstInt((*tile_type->memref_)->addr_);  // NOLINT(bugprone-unchecked-optional-access)
    std::string addr_str = FormatAddressHex(addr);
    std::ostringstream tassign;
    tassign << "TASSIGN(" << var_name << ", " << addr_str << ");";
    emitter_.EmitLine(tassign.str());
    // Track the address for tile yield/assignment (IfStmt uses TASSIGN instead of operator=)
    tile_addresses_[var_name] = addr_str;
  }
}

void CCECodegen::GenerateGlobalTensorTypeDeclaration(
    const std::string& var_name, const ir::TensorTypePtr& tensor_type,
    const std::optional<std::string>& base_pointer, const std::optional<std::string>& tensor_struct_ptr,
    const std::optional<std::vector<ir::ExprPtr>>& access_shape) {
  INTERNAL_CHECK(!var_name.empty()) << "Internal error: var_name cannot be empty";
  INTERNAL_CHECK(tensor_type != nullptr) << "Internal error: tensor_type is null";

  // Check if all tensor shape dims are static (ConstInt)
  bool all_static = true;
  for (const auto& dim : tensor_type->shape_) {
    if (!std::dynamic_pointer_cast<const ir::ConstInt>(dim)) {
      all_static = false;
      break;
    }
  }

  // Full tensor dimensions (only needed when tensor_struct_ptr is provided, for stride args)
  std::vector<int64_t> tensor_dims;
  if (all_static) {
    tensor_dims = ExtractShapeDimensions(tensor_type->shape_);
  }

  // Access shape overrides Shape<>/Stride<> type parameters when available
  std::vector<int64_t> shape_dims;
  if (access_shape.has_value()) {
    shape_dims = ExtractShapeDimensions(access_shape.value());
  } else if (all_static) {
    shape_dims = tensor_dims;
  } else {
    // Dynamic shapes without access_shape: use [1, 1] as a minimal placeholder
    // (the actual address is set by TASSIGN at runtime, shape only affects type template)
    shape_dims = {1, 1};
  }

  // Get element type
  std::string element_type = tensor_type->dtype_.ToCTypeString();

  // Generate unique type names for this variable
  std::string shape_type_name = var_name + "ShapeDim5";
  std::string stride_type_name = var_name + "StrideDim5";
  std::string global_type_name = var_name + "Type";

  // Generate Shape type alias
  std::string shape_type = type_converter_.GenerateShapeType(shape_dims);
  std::ostringstream shape_alias;
  shape_alias << "using " << shape_type_name << " = " << shape_type << ";";
  emitter_.EmitLine(shape_alias.str());

  // Generate Stride type alias
  // In single-file mode, use static strides (no Tensor struct for dynamic strides)
  std::string stride_type;
  if (single_file_mode_) {
    std::ostringstream oss;
    oss << "Stride<";
    const size_t target_dims = 5;
    size_t n = shape_dims.size();

    if (force_dn_layout_ && n == 2) {
      // DN (column-major) strides for 2D: [1, dim0] (column-stride=1, row-stride=dim0)
      for (size_t i = 0; i < target_dims - n; ++i) {
        oss << shape_dims[0] << ", ";
      }
      oss << "1, " << shape_dims[0];
    } else {
      // ND (row-major) strides: stride[i] = product(shape[i+1..n-1])
      for (size_t i = 0; i < target_dims - n; ++i) {
        oss << "1, ";
      }
      for (size_t i = 0; i < n; ++i) {
        int64_t stride = 1;
        for (size_t j = i + 1; j < n; ++j) {
          stride *= shape_dims[j];
        }
        oss << stride;
        if (i < n - 1) oss << ", ";
      }
    }
    oss << ">";
    stride_type = oss.str();
  } else {
    stride_type = type_converter_.GenerateStrideType(shape_dims);
  }
  std::ostringstream stride_alias;
  stride_alias << "using " << stride_type_name << " = " << stride_type << ";";
  emitter_.EmitLine(stride_alias.str());

  // Determine layout: DN if last dim is 1 or if tensor is in dn_tensors_ set
  if (*shape_dims.rbegin() == 1 || force_dn_layout_) {
    stride_type_name += ", Layout::DN";
  }

  // Generate GlobalTensor type alias
  std::ostringstream global_type_alias;
  global_type_alias << "using " << global_type_name << " = GlobalTensor<" << element_type << ", "
                    << shape_type_name << ", " << stride_type_name << ">;";
  emitter_.EmitLine(global_type_alias.str());

  // Generate GlobalTensor instance
  std::ostringstream global_instance;
  global_instance << global_type_name << " " << var_name << "(";
  if (base_pointer.has_value()) {
    global_instance << base_pointer.value();
  }
  if (tensor_struct_ptr.has_value()) {
    // Use original tensor ndim for stride indices (strides come from the full tensor struct)
    size_t ndim = tensor_type->shape_.size();
    global_instance << ", {}, {";
    for (size_t i = 0; i < ndim; i++) {
      global_instance << "static_cast<int64_t>(" << tensor_struct_ptr.value() << "->strides["
                      << std::to_string(i) << "])";
      if (i != ndim - 1) {
        global_instance << ", ";
      }
    }
    global_instance << "}";
  }
  global_instance << ");";
  emitter_.EmitLine(global_instance.str());

  // Register pointer mapping if base_pointer provided
  if (base_pointer.has_value()) {
    context_.RegisterPointer(var_name, base_pointer.value());
  }

  // Register both pointer and Tensor struct mappings if provided
  if (tensor_struct_ptr.has_value()) {
    // Register Tensor struct pointer for stride access
    context_.RegisterTensorStruct(var_name, tensor_struct_ptr.value());
  }
}

}  // namespace codegen

}  // namespace pypto
